"""added assets file info

Revision ID: f1e51ad4f794
Revises: 83f32a82a6a3
Create Date: 2024-12-17 22:17:14.567997

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f1e51ad4f794'
down_revision = '83f32a82a6a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('assets', sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('assets', sa.Column('base64_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'base64_data')
    op.drop_column('assets', 'content_type')
    op.drop_column('assets', 'filename')
    # ### end Alembic commands ###
